<?php
global $errors;
$current_user = wp_get_current_user();

//is_admin and GET action are both checked before file is included.
if(current_user_can('install_themes')) {
	$child_theme_created = wlfw_make_child_theme('WLFW-'.get_bloginfo('name'), 'Whitelabel Framework child theme created to customize the current website. This theme was generated by Whitelabel Themes one-click-child-theme option!', $current_user->user_login );
	if(!is_wp_error($child_theme_created)) {
		die ('
			<html>
			<head>
				<meta http-equiv="refresh" content="1;url='.get_admin_url().'themes.php?activated=true">
			</head>
			<body>
				<div style="margin: 20% auto; width: 50%; text-align: center;"><h1>Child Theme Created!</h1><h3>Activing '.$child_theme_created['new_theme'].' now...</h3><p>Redirecting you to '.get_admin_url().'themes.php?activated=true'.'</p></div>
			</body>
			</html>
			');
	}
	else {
		$errors = $child_theme_created;
	}
}

function wlfw_make_child_theme( $new_theme_title, $new_theme_description, $new_theme_author ) {
	$parent_theme = wp_get_theme();
	if($parent_theme->parent()) 
		return new WP_Error( 'Theme Error', __('WordPress does not currently support theme building on children of children, ie Grandchildren themes.', SM_SITEOP_PREFIX) );

	$parent_theme_title = get_current_theme();
	$parent_theme_template = get_template(); //Doesn't play nice with the grandkids
	$parent_theme_name = get_stylesheet();

	// Turn a theme name into a directory name
	$new_theme_name = sanitize_title( $new_theme_title );
	$theme_root = get_theme_root();

	// Validate theme name
	$new_theme_path = $theme_root.'/'.$new_theme_name;
	$i = 0;
	while( file_exists( $new_theme_path ) ) {
		$i++;
		$new_theme_path = $new_theme_path . $i;
	}
	if(!empty($i)) $new_theme_name = $new_theme_name.$i;

if(isset($_GET['test'])) { echo '<pre>';var_export($new_theme_path); }

	mkdir( $new_theme_path );

	// Make style.css
	ob_start();
	require('child-theme-oneclick-css.php');
	$css = ob_get_clean();
	file_put_contents( $new_theme_path.'/style.css', $css );
	
	//make functions.php
	file_put_contents( $new_theme_path.'/functions.php', '<?php'.PHP_EOL );

	// Copy screenshot
	$parent_theme_screenshot = $theme_root.'/'.$parent_theme_name.'/screenshot.png';
	if ( file_exists( $parent_theme_screenshot ) ) {
		copy( $parent_theme_screenshot, $new_theme_path.'/screenshot.png' );
	} elseif (file_exists( $parent_theme_screenshot = $theme_root.'/'.$parent_theme_template.'/screenshot.png' ) ) {
		copy( $parent_theme_screenshot, $new_theme_path.'/screenshot.png' );
	}

	// Make child theme an allowed theme (network enable theme)
	/*
	$allowed_themes = get_site_option( 'allowedthemes' );
	$allowed_themes[ $new_theme_name ] = true;
	update_site_option( 'allowedthemes', $allowed_themes );
	*/
	$the_theme = array(
		'parent_template'    => $parent_theme_template,
		'parent_theme'       => $parent_theme_name,
		'new_theme'          => $new_theme_name,
		'new_theme_path'     => $new_theme_path,
		'new_theme_title'	 => $new_theme_title,
	);

	switch_theme( $parent_theme_name, $new_theme_name );

if(isset($_GET['test'])) { $ct = wp_get_theme(); var_export($ct);exit; }

	return array(
		'parent_template'    => $parent_theme_template,
		'parent_theme'       => $parent_theme_name,
		'new_theme'          => $new_theme_name,
		'new_theme_path'     => $new_theme_path,
		'new_theme_title'	 => $new_theme_title,
	);
}
